### ISSUE TITLE
GetObjectRequest error creating request object

### ISSUE THREAD

**Issue by mikesparr** [NationalAssociationOfRealtors/libRETS#33]
Oddly this worked fine with `1.6.1` and we haven't changed anything, but are pulling a LOT (300 million +) photos from dozens of feeds.  We started seeing these errors in logs and unsure how to interpret. I asked user group and no response so posting issue here.

~~~
rets_client.pyc: ERROR: Error [in method 'new_GetObjectRequest', argument 1 of type 'std::string'] librets.GetObjectRequest(Agent, Photo) for rec_id [259510440017078]
rets_client.pyc: DEBUG: Traceback (most recent call last):
  File "/Users/mike/Work/etl-service/etlservice/util/rets_client.py", line 919, in _get_photos
    request = librets.GetObjectRequest(ptype.decode('utf-8'), otype.decode('utf-8'))
  File "/Library/Python/2.7/site-packages/librets.py", line 1274, in __init__
    this = _librets.new_GetObjectRequest(resource, type)
TypeError: in method 'new_GetObjectRequest', argument 1 of type 'std::string'
~~~

Librets 1.6.1 on Ubuntu Linux and errors for both Property and Agent photo pulls. Any idea what and why building the request object is failing and how to diagnose this?  Is it something like MLS system firewall or actual bad data type passed as argument in function?

**Comment by mikesparr** [comment]
I see here: https://github.com/NationalAssociationOfRealtors/libRETS/blob/master/project/librets/src/GetObjectRequest.cpp

that the two string parameters are all that is required so unclear why TypeError occurring when we pass strings "Property" and "Photo" or "Agent" and "Photo" (or "AgentPhoto") respectively.

**Comment by mikesparr** [comment]
Don't know SWIG but curious if a recent apt-get update/upgrade updated swig and changed behavior? That's only thing I can think of why this occurred. Appreciate insight into swig and perhaps what version you're testing with on Linux.

http://stackoverflow.com/questions/12236150/string-arguments-are-not-recognized-by-swig

**Comment by mikesparr** [comment]
This fails our automated tests when run on a Macbook Pro too so not OS or network related and neither was a new version of librets recently installed. All of a sudden they started failing 2 days ago and we're baffled?  Appreciate any tips and we might try to update to 1.6.2 just to clear cobwebs.

**Comment by mikesparr** [comment]
Checking string types and forcing ASCII type appears to resolve issue. Otherwise they are typed as `unicode` and appears to fail with the SWIG/C type checking. Closing - woo hoo!
