### ISSUE TITLE
[OS X 10.12.6] Python Import Failing

### ISSUE THREAD

**Issue by bgirer** [NationalAssociationOfRealtors/libRETS#53]
`import librets` is producing an ImportError: 

```
>>> import librets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "librets.py", line 17, in <module>
    _librets = swig_import_helper()
  File "librets.py", line 16, in swig_import_helper
    return importlib.import_module('_librets')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_librets.so, 2): Symbol not found: __ZN7librets11RetsSession11GetMetadataERSo
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_librets.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_librets.so
```

Here was my installation workflow:

1. Downloaded master branch of the git repo as .zip, unpacked
2. Ran `./autogen.sh`
3. Ran `./configure --disable-debug --enable-shared_dependencies --prefix=/opt/local --with-boost-prefix=/opt/local --disable-dotnet --disable-java --disable-perl --disable-php --disable-ruby --disable-python3`
4. Ran `make`, then `sudo make install`
5. Ran `python setup.py install` from build/swig/python

No idea where to go from this error, Googling returned nothing. Any help would be much appreciated!

**Comment by bgirer** [comment]
Solved
